### ISSUE TITLE
kinetic version breaks rqt_graph

### ISSUE THREAD

**Issue by harvcode** [ros-visualization/python_qt_binding#38] opened 2016-05-02 12:44 UTC
command ran: rosrun rqt_graph rqt_graph
error: 

`  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 83, in load
    raise e
ImportError: cannot import name QGraphicsPathItem
`

error originates from here:

` File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_dotgraph/edge_item.py", line 32, in <module>
    from python_qt_binding.QtGui import QBrush, QGraphicsPathItem, QGraphicsPolygonItem, QGraphicsSimpleTextItem, QPainterPath, QPen, QPolygonF
ImportError: cannot import name QGraphicsPathItem
`

**Comment by dirk-thomas** [comment] 2016-05-02 16:15
It seems like you are using an older version of `qt_dotgraph`. Version 0.3.2 imports that class from QWidgets: https://github.com/ros-visualization/qt_gui_core/blob/kinetic-devel/qt_dotgraph/src/qt_dotgraph/edge_item.py#L33

**Comment by harvcode** [comment] 2016-05-03 08:43
I am using the version that gets installed automatically from the kinetic binaries, so perhaps the repository binaries need to be changed to reflect this?

**Comment by dirk-thomas** [comment] 2016-05-03 15:47
Please state the exact version number of  `qt_dotgraph` as well as `rqt_graph` you are using.

**Comment by tfoote** [comment] 2016-05-03 16:16
@harvcode The versions available from binary have changed recently. That's why we need to confirm the version on your system.

**Comment by harvcode** [comment] 2016-05-03 21:21
ros-kinetic-qt-dotgraph/xenial,now 0.3.2-0xenial-20160428-192006-0700 amd64 
ros-kinetic-rqt-graph/xenial,now 0.4.0-1xenial-20160429-165937-0700 amd64

**Comment by dirk-thomas** [comment] 2016-05-03 21:27
The code in the error message in your original comment (edge_item.py, line 32) does not match the code available in these versions. 

Version 0.3.0 has the line you quoted above: https://github.com/ros-visualization/qt_gui_core/blob/0.3.0/qt_dotgraph/src/qt_dotgraph/edge_item.py#L32

Version 0.3.1 as well as 0.3.2 have this instead which should work:
* https://github.com/ros-visualization/qt_gui_core/blob/0.3.1/qt_dotgraph/src/qt_dotgraph/edge_item.py#L32
* https://github.com/ros-visualization/qt_gui_core/blob/0.3.2/qt_dotgraph/src/qt_dotgraph/edge_item.py#L32

**Comment by harvcode** [comment] 2016-05-03 21:31
Just tried it again and I still get "ImportError: cannot import name QFormLayout".

Apt says I am up to date on both of those packages and lists those versions.

**Comment by dirk-thomas** [comment] 2016-05-03 21:55
Since the error is different then what you reported above please post the complete error message and steps you did to reproduce.

**Comment by harvcode** [comment] 2016-05-03 21:57
From command line: rqt
From menu: Plugins > Robot Tools > Controller Manager
Error appears in console.

**Comment by dirk-thomas** [comment] 2016-05-03 22:56
Please post the full error message.

**Comment by harvcode** [comment] 2016-05-03 23:03
`
PluginManager._load_plugin() could not load plugin "rqt_controller_manager/ControllerManager":
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 99, in load
    self._load()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 83, in load
    raise e
ImportError: cannot import name QFormLayout

RosPluginProvider.load(rqt_controller_manager/ControllerManager) exception raised in __builtin__.__import__(rqt_controller_manager.controller_manager, [ControllerManager]):
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 77, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/root/catkin_ws/src/ros_control/rqt_controller_manager/src/rqt_controller_manager/controller_manager.py", line 35, in <module>
    from python_qt_binding.QtGui import QCursor, QFont, QFormLayout, QHeaderView,\
ImportError: cannot import name QFormLayout`

**Comment by dirk-thomas** [comment] 2016-05-04 00:13
The stack trace indicates that the problem is in the package `rqt_controller_manager` which is in your local workspace (I assume it hasn't been released into Kinetic yet?). You might want to fill a ticket in the repository which contains that package: https://github.com/ros-controls/ros_control/issues

**Closed** 2016-05-04 00:14 UTC
Labels: invalid
