### ISSUE TITLE
catkin install, fails to create python install directory

### ISSUE THREAD

**Issue by jgoppert** [ros-visualization/python_qt_binding#18] opened 2015-01-17 09:05 UTC
I fixed this with the command:
mkdir -p ~/ros/install/python_qt_binding/lib/python2.7/dist-packages/

**Comment by dirk-thomas** [comment] 2015-02-04 19:32
Can you please describe what exact commands you ran when having the problem?

**Comment by jgoppert** [comment] 2015-02-04 19:41
I believe i was using the new catkin tools.

**Comment by dirk-thomas** [comment] 2015-02-04 19:43
Please provide enough information to easily reproduce your problem.

**Comment by jgoppert** [comment] 2015-02-04 19:48
This was too long ago for me to remember, you can close it if you like.

**Comment by dirk-thomas** [comment] 2015-02-04 20:02
Since I can build the package locally without a problem as well as the farm can build the binary packages I will close it.

If the problem occurs again please comment with more information and the ticket can be reopened.

**Closed by dirk-thomas** 2015-02-04 20:02 UTC

**Comment by fjonath1** [comment] 2016-02-16 23:06
I can reproduce this error. I'm using OSX El Capitan, system python.
Building with catkin tool without isolate config or catkin_make_isolate will not have any problem.
Here is how I reproduce this error
1. Install catkin tools
2. go to catkin_ws (which contains src/python_qt_binding. In my case, the folder name is ros_catkin_ws)
3. Run `catkin config --isolate-install --isolate-devel`
4. Run `catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release`
5. When building python_qt_binding, it will have this error
```
[python_qt_binding] ==> '/Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/build_env.sh /usr/bin/make install' in '/Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding'
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/_setup_util.py
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/env.sh
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/setup.bash
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/setup.sh
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/setup.zsh
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/.rosinstall
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/lib/pkgconfig/python_qt_binding.pc
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/share/python_qt_binding/cmake/python_qt_binding-extras.cmake
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/share/python_qt_binding/cmake/python_qt_bindingConfig.cmake
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/share/python_qt_binding/cmake/python_qt_bindingConfig-version.cmake
-- Installing: /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/share/python_qt_binding/package.xml
+ cd /Users/FelixJonathan/ros_catkin_ws/src/python_qt_binding
+ /usr/bin/env PYTHONPATH=/Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/genlisp/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/genpy/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/gencpp/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/genmsg/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/roscpp_serialization/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/rostime/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/roscpp_traits/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/message_generation/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/cpp_common/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/message_runtime/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/rosbuild/lib/python2.7/site-packages:/Users/FelixJonathan/ros_catkin_ws/install/catkin/lib/python2.7/site-packages CATKIN_BINARY_DIR=/Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding /usr/bin/python /Users/FelixJonathan/ros_catkin_ws/src/python_qt_binding/setup.py build --build-base /Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding install --prefix=/Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding --install-scripts=/Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/bin
running build
running build_py
creating /Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/lib
creating /Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/lib/python_qt_binding
copying src/python_qt_binding/__init__.py -> /Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/lib/python_qt_binding
copying src/python_qt_binding/binding_helper.py -> /Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/lib/python_qt_binding
copying src/python_qt_binding/QtBindingHelper.py -> /Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/lib/python_qt_binding
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/lib/python2.7/site-packages/test-easy-install-13075.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/FelixJonathan/ros_catkin_ws/install/python_qt_binding/lib/python2.7/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):
  
  execute_process(/Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:132 (include)
  


make: *** [install] Error 1
[python_qt_binding] <== '/Users/FelixJonathan/ros_catkin_ws/build/python_qt_binding/build_env.sh /usr/bin/make install' failed with return code '2'
                                                                                 
Failed   <== python_qt_binding                [ 5.6 seconds ]                   

```

I can fix this easily by making new directory called `python2.7` in `ros_catkin_ws/install/python_qt_binding/lib` and `site-packages` directory inside of python 2.7

**Comment by dirk-thomas** [comment] 2016-02-16 23:20
Please fill the ticket against [catkin_tools](https://github.com/catkin/catkin_tools). Since it is not recommended to use it yet I won't have time to look into the problem which might be just related to this new tools.
