### ISSUE TITLE
cannot import QAction on kinetic

### ISSUE THREAD

**Issue by jgoppert** [ros-visualization/python_qt_binding#36] opened 2016-04-20 21:21 UTC
```
$ rqt_bag
Traceback (most recent call last):
  File "/home/jgoppert/git/catkin/devel/bin/rqt_bag", line 6, in <module>
    exec(fh.read())
  File "<string>", line 5, in <module>
  File "/home/jgoppert/git/catkin/devel/lib/python2.7/dist-packages/rqt_bag/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 35, in <module>
  File "/home/jgoppert/git/catkin/src/rqt_common_plugins/rqt_bag/src/rqt_bag/plugins/topic_message_view.py", line 34, in <module>
    from python_qt_binding.QtGui import QAction, QIcon, QToolBar
ImportError: cannot import name QAction
```

**Comment by dirk-thomas** [comment] 2016-04-20 21:22
Duplicate of ros-visualization/rqt_common_plugins#363

**Closed** 2016-04-20 21:22 UTC
